### ISSUE TITLE
Incompatible with latest IntelliJ 2020.3.1

### ISSUE THREAD

**Issue by Joshua-F** [amzn/ion-intellij-plugin#12]
After upgrading IntelliJ to 2020.3.1 you are greeted with a message saying that the plugin "was explicitly marked as incompatible with the current version of the IDE".

**Comment by gosre** [comment]
Getting the same issue

**Comment by tiredasf** [comment]
Also have the same issue.

**Comment by tgregg** [comment]
Thanks for the report. We will work on a fix and update this issue once it is available.

**Comment by branch-tim** [comment]
The latest code on master works for me, with IDEA 2020.3.3.

**Comment by hiljusti** [comment]
What's the expected time between a version of IDEA updating (or Android Studio) and getting a plugin update out?

I'm on Android Studio build 202, but I see on [this page](https://plugins.jetbrains.com/plugin/8409-amazon-ion-intellij-idea-plugin/versions) that the latest supported build is 201.
