### ISSUE TITLE
Plugin doesn't work in IntelliJ 2021.3

### ISSUE THREAD

**Issue by r0b0ji** [amzn/ion-intellij-plugin#23]
I upgraded from 2021.1 to 2021.3 and after that the plugin was disabled and showing a red error in plugins saying "Incompatible: requires IDE version 212.* or earlier"

After uninstalling now it is no longer available in plugins to re-install.

**Comment by r0b0ji** [comment]
I was able to build it by just changing this line https://github.com/amzn/ion-intellij-plugin/blob/55eface65b9ce08b7b93209d1e12eb418ac1ac0e/build.gradle.kts#L36 from 212.* to 213.*

I installed the built plugin from disk and it is working.

**Comment by mina-asham** [comment]
This was fixed here: https://github.com/amzn/ion-intellij-plugin/pull/24, we just need a new release published now :)

**Comment by mina-asham** [comment]
Seems like the new release is here: https://plugins.jetbrains.com/plugin/8409-amazon-ion, so we should probably close this one :)
