### ISSUE TITLE
Plugin not suggested when opening .ion file under IntelliJ-2020.2 (previous functionality)

### ISSUE THREAD

**Issue by jayessdeesea** [amzn/ion-intellij-plugin#9]
Also, plugin does not show up under File->Settings->Plugins->Marketplace

I was able to manually install the plugin

**Comment by hiljusti** [comment]
The plugin got updated to support the most recent versions of IntelliJ (2021.1 and 2021.2) and when I tried it out, IntelliJ suggested the Amazon Ion plugin for a .ion file. (Tested in IntelliJ and Android Studio)
